include "common.conf"

appName="sdltc-frontend"

# Play 2.5 Upgrade
play.modules.enabled += "com.kenshoo.play.metrics.PlayModule"
play.http.requestHandler = "play.api.http.GlobalSettingsHttpRequestHandler"

application.router=prod.Routes

application.global=config.FrontendGlobal

# Assets configuration
# ~~~~~
# For now just some (very short) test settings to prove it works as expected - i.e. control over the individual resources
"assets.cache./public/index.html"="public, max-age=900, s-maxage=900" # 15 minutes
"assets.cache./public/javascript/v11-calc.js"="public, max-age=31536000" # 1 year (365 days)
"assets.cache./public/javascript/v11-calc-templates.js"="public, max-age=31536000" # 1 year (365 days)

# Override the allowed cache types to include HTML for this application
caching.allowedContentTypes=["image/", "text/css", "application/javascript", "text/html"]

Dev {

    assets {
      version = ${?Prod.assets.version}
      version = ${?ASSETS_FRONTEND_VERSION}
      url = "http://localhost:9032/assets/"
    }

    google-analytics {
      token=N/A
      host=auto
    }

    contact-frontend {
      host = "http://localhost:9250"
    }
}

Prod {

    microservice {
      metrics {
        graphite {
          host = graphite
          port = 2003
          prefix = play.${appName}.
          enabled = true
        }
      }
    }

    google-analytics {
      token=N/A
      host=auto
    }

    assets {
      url=/assets/
      version = "2.185.0"
    }

}

Test {

  assets {
    url=/assets/
    version = "2.185.0"
  }

  google-analytics {
    token=N/A
    host=auto
  }

}


# By default all controllers will have logging enabled.
# The below controllers are the default exceptions to this rule.

controllers {
  com.kenshoo.play.metrics.MetricsController = {
    needsLogging = false
  }
  uk.gov.hmrc.play.health.AdminController = {
    needsLogging = false
  }
}

# Metrics plugin settings - graphite reporting is configured on a per env basis
metrics {
  name = ${appName}
  rateUnit = SECONDS
  durationUnit = SECONDS
  showSamples = true
  jvm = true
  enabled = true
  extraMeasured = []
}