include "common.conf"

appName="sdltc-frontend"

# Play 2.5 Upgrade
play.modules.enabled += "com.kenshoo.play.metrics.PlayModule"
play.http.requestHandler = "play.api.http.GlobalSettingsHttpRequestHandler"
play.filters.enabled += "play.filters.headers.SecurityHeadersFilter"
play.filters.headers.contentSecurityPolicy = "default-src 'self' 'unsafe-inline' localhost:9000 localhost:9090 www.google-analytics.com ajax.googleapis.com analytics.analytics-egain.com cdn.optimizely.com data:"

application.router=prod.Routes

application.global=config.FrontendGlobal

# Assets configuration
# ~~~~~
# For now just some (very short) test settings to prove it works as expected - i.e. control over the individual resources
"assets.cache./public/index.html"="public, max-age=900, s-maxage=900" # 15 minutes
"assets.cache./public/javascript/calc.js"="public, max-age=31536000" # 1 year (365 days)
"assets.cache./public/javascript/calc-templates.js"="public, max-age=31536000" # 1 year (365 days)

# Override the allowed cache types to include HTML for this application
caching.allowedContentTypes=["image/", "text/css", "application/javascript", "text/html"]

run.mode: Prod

Dev {

    auditing {
      enabled = false
      traceRequests = true
      consumer {
        baseUri {
          host = localhost
          port = 8100
        }
      }
    }

    assets {
      version = ${?Prod.assets.version}
      version = ${?ASSETS_FRONTEND_VERSION}
      url = "http://localhost:9032/assets/"
    }

    google-analytics {
      token=N/A
      host=auto
    }

    contact-frontend {
      host = "http://localhost:9250"
    }

    optimizely {
      projectId = "123456789"
    }
}

Prod {

    microservice {
      metrics {
        graphite {
          host = graphite
          port = 2003
          prefix = play.${appName}.
          enabled = true
        }
      }
    }

    auditing {
      enabled = true
      traceRequests = true
      consumer {
        baseUri {
          host = datastream.protected.mdtp
          port = 80
        }
      }
    }

    optimizely {
      projectId = "123456789"
    }

    google-analytics {
      token=N/A
      host=auto
    }

    assets {
      url=/assets/
      version = "2.254.0"
    }

}

Test {

  assets {
    url = /assets/
    version = "2.254.0"
  }

  google-analytics {
    token = N/A
    host = auto
  }

  auditing {
    enabled = false
    traceRequests = true
    consumer {
      baseUri {
        host = localhost
        port = 8100
      }
    }
  }

  optimizely {
    projectId = "123456789"
  }

}


# By default all controllers will have logging enabled.
# The below controllers are the default exceptions to this rule.

controllers {
  com.kenshoo.play.metrics.MetricsController = {
    needsLogging = false
  }
  uk.gov.hmrc.play.health.AdminController = {
    needsLogging = false
  }
}

# Metrics plugin settings - graphite reporting is configured on a per env basis
metrics {
  name = ${appName}
  rateUnit = SECONDS
  durationUnit = SECONDS
  showSamples = true
  jvm = true
  enabled = true
  extraMeasured = []
}
