include "frontend.conf"

appName="sdltc-frontend"

application.router=prod.Routes

play.application.loader = "uk.gov.hmrc.play.bootstrap.ApplicationLoader"
play.http.requestHandler = "uk.gov.hmrc.play.bootstrap.http.RequestHandler"
play.modules.enabled += "uk.gov.hmrc.play.bootstrap.AuditModule"
play.modules.enabled += "uk.gov.hmrc.play.bootstrap.HttpClientModule"
play.modules.enabled += "uk.gov.hmrc.play.bootstrap.graphite.GraphiteMetricsModule"

play.modules.enabled += "uk.gov.hmrc.play.bootstrap.FrontendModule"
play.http.filters = "config.SDLTCFilters"

play.http.errorHandler = "config.SDLTCErrorHandler"

play.filters.enabled += "play.filters.headers.SecurityHeadersFilter"
play.filters.headers.contentSecurityPolicy = "base-uri 'self';block-all-mixed-content;child-src 'none';connect-src 'self' https://www.google-analytics.com;default-src 'self' 'unsafe-inline' localhost:9250 localhost:9514 www.google-analytics.com analytics.analytics-egain.com data:;form-action 'self';frame-ancestors 'none';script-src 'self' 'unsafe-inline' ajax.googleapis.com www.google-analytics.com cdn.optimizely.com; object-src 'none';"


# Assets configuration
# ~~~~~
# For now just some (very short) test settings to prove it works as expected - i.e. control over the individual resources
"assets.cache./public/index.html"="public, max-age=900, s-maxage=900" # 15 minutes
"assets.cache./public/javascript/calc.js"="public, max-age=31536000" # 1 year (365 days)
"assets.cache./public/javascript/calc-templates.js"="public, max-age=31536000" # 1 year (365 days)

# Override the allowed cache types to include HTML for this application
caching.allowedContentTypes=["image/", "text/css", "application/javascript", "text/html"]


microservice {
  metrics {
    graphite {
      host = graphite
      port = 2003
      prefix = play.${appName}.
      enabled = false
    }
    name = ${appName}
    rateUnit = SECONDS
    durationUnit = SECONDS
    showSamples = true
    jvm = true
    enabled = false
    extraMeasured = []
  }
}

google-analytics {
  token=N/A
  host=auto
}


assets {
  version = "2.254.0"
  version = ${?ASSETS_FRONTEND_VERSION}
  url = "http://localhost:9032/assets/"
}

optimizely {
  projectId = "123456789"
}

auditing {
  enabled=false
  traceRequests=true
  consumer {
    baseUri {
      host = localhost
      port = 8100
    }
  }
}

# By default all controllers will have logging enabled.
# The below controllers are the default exceptions to this rule.

controllers {
  uk.gov.hmrc.play.health.AdminController = {
    needsLogging = false
  }

  uk.gov.hmrc.play.health.HealthController = {
    needsAuth = false
  }
}

feedback-survey-frontend {
  url="http://localhost:9514/feedback/SDLTC"
}

contact-frontend {
  protocol = https
  host = ""
  port = 443
}
