# Copyright 2025 HM Revenue & Customs
#

include "frontend.conf"

  appName="sdltc-frontend"

  play.http.router="scalabuild.Routes"

  mongodb {
    # Default local development URI
    uri = "mongodb://localhost:27017/"${appName}
    timeToLiveInMinutes            = 15
  }


  play.modules.enabled += "uk.gov.hmrc.mongo.play.PlayMongoModule"
  play.modules.enabled += "config.scalabuild.Module"
  play.modules.enabled += "uk.gov.hmrc.play.bootstrap.HttpClientV2Module"


  ftb-limit {
    startDate = "2022-09-23"
    endDate =  "2025-04-01"
    highValue = 625000
    lowValue = 500000
  }